export const tours = [
  {
    id: 1,
    title: "Hood River",
    price: 99.95,
    image: "/images/ammie-ngo-vcu-OZBxxRk-unsplash.jpg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia. labore et dolore magna aliqua. at vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque. gravida cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. gravida cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. gravida cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus.",
  },
  {
    id: 2,
    title: "Canyonlands",
    price: 199.95,
    image: "/images/andy-holmes-0LJCEORiYg8-unsplash.jpg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia. velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. consectetur adipisicing elit. Asperiores, officia. reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    id: 3,
    title: "Banff",
    price: 299.95,
    image: "/images/bernardo-lorena-ponte-ddcbYY4tLyU-unsplash.jpg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia. velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. mollit anim id est laborum.",
  },
  {
    id: 4,
    title: "The Beach",
    price: 399.95,
    image: "/images/bing-hui-yau-y85Tir86Q34-unsplash.jpg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia. elit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. qui officia deserunt mollit anim id est laborum. while reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. ut labore et dolore magna aliqua.",
  },
  {
    id: 5,
    title: "The Fog",
    price: 499.95,
    image: "/images/harold-eggar-oIVpygLFUJg-unsplash.jpg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia.",
  },
  {
    id: 6,
    title: "The Wolf",
    price: 599.95,
    image: "/images/il-vagabiondo-8eNt0CQamB0-unsplash.jpg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia. do eiusmod tempor incididunt ut labore et dolore magna aliqua. at vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque. gravida cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus.",
  },
  {
    id: 7,
    title: "The Lion",
    price: 699.95,
    image: "/images/priscilla-du-preez-KoF1cXdF9Ws-unsplash.jpg",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, officia. reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];
